Update default scope string. #133
microsoft/rest-api-fuzz-testing pull request #134
Opened 2021-02-16 17:31 UTC by mgreisen

2021-02-16 17:58 UTC, stishkin approved these changes

2021-02-17 18:17 UTC, stishkin requested changes
You need to change RAFT deployment script as well. When we publish service principal to keyvault it needs to have audience

2021-02-17 18:19 UTC, stishkin approved these changes

2021-02-17 18:21 UTC, mgreisen commented
> You need to change RAFT deployment script as well. When we publish service principal to keyvault it needs to have audience

The current behavior is maintained where we default the client id _unless_ an audience is supplied.

2021-02-19 21:15 UTC, merged